name: GEOMETOR
motto: exploring<br>the architecture of<br>all that is
logo: logo.png
email: info@geometor.com
social:
  facebook: phiarchitect
  twitter: phi_architect
  linkedin: phiarchitect
  github: geometor
  patreon: phiarchitect
  youtube: UCYzRQS16EBmsbKuyKMFHSFQ
owa:
  siteId: 966594a8fb31bde819b2f9ec9210b821
  trackPageView: true
  trackCLicks: false
  trackDomStream: false
google_search: rx3g9yar1U6omp_jO04YkOVZuZyNJO07d00DIHglZ1Q
